package au.net.transtech.tuan.pojo.postcode;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.2.3
 * Fri Aug 29 10:04:39 EST 2014
 * Generated source version: 2.2.3
 * 
 */
 
@WebService(targetNamespace = "http://www.ssw.com.au/PostcodeWebservice", name = "PostcodeServiceHttpPost")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface PostcodeServiceHttpPost {

    @WebResult(name = "DataSet", targetNamespace = "http://www.ssw.com.au/PostcodeWebservice", partName = "Body")
    @WebMethod(operationName = "GetPostcodeAndSuburbForAustralia")
    public DataSet getPostcodeAndSuburbForAustralia(
        @WebParam(partName = "txtSuburb", name = "txtSuburb", targetNamespace = "")
        java.lang.String txtSuburb,
        @WebParam(partName = "txtState", name = "txtState", targetNamespace = "")
        java.lang.String txtState,
        @WebParam(partName = "txtPostCode", name = "txtPostCode", targetNamespace = "")
        java.lang.String txtPostCode
    );
}
