
/*
 * 
 */

package au.net.transtech.tuan.pojo.postcode;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.3
 * Thu Sep 04 22:28:27 EST 2014
 * Generated source version: 2.2.3
 * 
 */


@WebServiceClient(name = "PostcodeService", 
                  wsdlLocation = "file:/home/tuan/workspace/simple-pojo/src/main/resources/postcode/PostCodeService.wsdl",
                  targetNamespace = "http://www.ssw.com.au/PostcodeWebservice") 
public class PostcodeService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://www.ssw.com.au/PostcodeWebservice", "PostcodeService");
    public final static QName PostcodeServiceSoap = new QName("http://www.ssw.com.au/PostcodeWebservice", "PostcodeServiceSoap");
    public final static QName PostcodeServiceSoap12 = new QName("http://www.ssw.com.au/PostcodeWebservice", "PostcodeServiceSoap12");
    public final static QName PostcodeServiceHttpPost = new QName("http://www.ssw.com.au/PostcodeWebservice", "PostcodeServiceHttpPost");
    public final static QName PostcodeServiceHttpGet = new QName("http://www.ssw.com.au/PostcodeWebservice", "PostcodeServiceHttpGet");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/tuan/workspace/simple-pojo/src/main/resources/postcode/PostCodeService.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:/home/tuan/workspace/simple-pojo/src/main/resources/postcode/PostCodeService.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public PostcodeService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PostcodeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PostcodeService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns PostcodeServiceSoap
     */
    @WebEndpoint(name = "PostcodeServiceSoap")
    public PostcodeServiceSoap getPostcodeServiceSoap() {
        return super.getPort(PostcodeServiceSoap, PostcodeServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PostcodeServiceSoap
     */
    @WebEndpoint(name = "PostcodeServiceSoap")
    public PostcodeServiceSoap getPostcodeServiceSoap(WebServiceFeature... features) {
        return super.getPort(PostcodeServiceSoap, PostcodeServiceSoap.class, features);
    }
    /**
     * 
     * @return
     *     returns PostcodeServiceSoap
     */
    @WebEndpoint(name = "PostcodeServiceSoap12")
    public PostcodeServiceSoap getPostcodeServiceSoap12() {
        return super.getPort(PostcodeServiceSoap12, PostcodeServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PostcodeServiceSoap
     */
    @WebEndpoint(name = "PostcodeServiceSoap12")
    public PostcodeServiceSoap getPostcodeServiceSoap12(WebServiceFeature... features) {
        return super.getPort(PostcodeServiceSoap12, PostcodeServiceSoap.class, features);
    }
    /**
     * 
     * @return
     *     returns PostcodeServiceHttpPost
     */
    @WebEndpoint(name = "PostcodeServiceHttpPost")
    public PostcodeServiceHttpPost getPostcodeServiceHttpPost() {
        return super.getPort(PostcodeServiceHttpPost, PostcodeServiceHttpPost.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PostcodeServiceHttpPost
     */
    @WebEndpoint(name = "PostcodeServiceHttpPost")
    public PostcodeServiceHttpPost getPostcodeServiceHttpPost(WebServiceFeature... features) {
        return super.getPort(PostcodeServiceHttpPost, PostcodeServiceHttpPost.class, features);
    }
    /**
     * 
     * @return
     *     returns PostcodeServiceHttpGet
     */
    @WebEndpoint(name = "PostcodeServiceHttpGet")
    public PostcodeServiceHttpGet getPostcodeServiceHttpGet() {
        return super.getPort(PostcodeServiceHttpGet, PostcodeServiceHttpGet.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PostcodeServiceHttpGet
     */
    @WebEndpoint(name = "PostcodeServiceHttpGet")
    public PostcodeServiceHttpGet getPostcodeServiceHttpGet(WebServiceFeature... features) {
        return super.getPort(PostcodeServiceHttpGet, PostcodeServiceHttpGet.class, features);
    }

}
