package au.net.transtech.tuan.pojo.eplan;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebParam.Mode;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.3
 * Fri Aug 29 11:52:09 EST 2014
 * Generated source version: 2.2.3
 * 
 */
 
@WebService(targetNamespace = "http://www.transtech.net.au/", name = "ePlanWebServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface EPlanWebServiceSoap {

    @WebResult(name = "getNextRequiredRestResponse", targetNamespace = "http://www.transtech.net.au/", partName = "parameters")
    @WebMethod(action = "http://www.transtech.net.au/getNextRequiredRest")
    public GetNextRequiredRestResponse getNextRequiredRest(
        @WebParam(partName = "parameters", name = "getNextRequiredRest", targetNamespace = "http://www.transtech.net.au/")
        GetNextRequiredRest parameters
    );

    @WebResult(name = "ePlanMessageResponse", targetNamespace = "http://www.transtech.net.au/", partName = "parameters")
    @WebMethod(action = "http://www.transtech.net.au/ePlanMessage")
    public EPlanMessageResponse ePlanMessage(
        @WebParam(partName = "parameters", name = "ePlanMessage", targetNamespace = "http://www.transtech.net.au/")
        EPlanMessage parameters
    );
}
