package au.net.transtech.tuan.pojo.eplan;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebParam.Mode;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.3
 * Fri Aug 29 10:04:40 EST 2014
 * Generated source version: 2.2.3
 * 
 */
 
@WebService(targetNamespace = "http://www.transtech.net.au/", name = "ePlanWebServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface EPlanWebServiceSoap {

    @RequestWrapper(localName = "getNextRequiredRest", targetNamespace = "http://www.transtech.net.au/", className = "au.net.transtech.tuan.pojo.eplan.GetNextRequiredRest")
    @ResponseWrapper(localName = "getNextRequiredRestResponse", targetNamespace = "http://www.transtech.net.au/", className = "au.net.transtech.tuan.pojo.eplan.GetNextRequiredRestResponse")
    @WebMethod(action = "http://www.transtech.net.au/getNextRequiredRest")
    public void getNextRequiredRest(
        @WebParam(name = "DriverId", targetNamespace = "http://www.transtech.net.au/")
        int driverId,
        @WebParam(name = "lastCheckpoint", targetNamespace = "http://www.transtech.net.au/")
        javax.xml.datatype.XMLGregorianCalendar lastCheckpoint,
        @WebParam(mode = WebParam.Mode.OUT, name = "getNextRequiredRestResult", targetNamespace = "http://www.transtech.net.au/")
        javax.xml.ws.Holder<javax.xml.datatype.XMLGregorianCalendar> getNextRequiredRestResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "upToDateAt", targetNamespace = "http://www.transtech.net.au/")
        javax.xml.ws.Holder<javax.xml.datatype.XMLGregorianCalendar> upToDateAt,
        @WebParam(mode = WebParam.Mode.OUT, name = "secondsRestRequired", targetNamespace = "http://www.transtech.net.au/")
        javax.xml.ws.Holder<java.lang.Integer> secondsRestRequired,
        @WebParam(mode = WebParam.Mode.OUT, name = "ruleSummary", targetNamespace = "http://www.transtech.net.au/")
        javax.xml.ws.Holder<java.lang.String> ruleSummary
    );

    @WebResult(name = "ePlanMessageResult", targetNamespace = "http://www.transtech.net.au/")
    @RequestWrapper(localName = "ePlanMessage", targetNamespace = "http://www.transtech.net.au/", className = "au.net.transtech.tuan.pojo.eplan.EPlanMessage")
    @ResponseWrapper(localName = "ePlanMessageResponse", targetNamespace = "http://www.transtech.net.au/", className = "au.net.transtech.tuan.pojo.eplan.EPlanMessageResponse")
    @WebMethod(action = "http://www.transtech.net.au/ePlanMessage")
    public boolean ePlanMessage(
        @WebParam(name = "message", targetNamespace = "http://www.transtech.net.au/")
        java.lang.String message
    );
}
