package au.net.transtech.tuan.pojo.abn;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.3
 * Fri Sep 05 00:13:56 EST 2014
 * Generated source version: 2.2.3
 * 
 */
 
@WebService(targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/", name = "ABRXMLSearchSoap")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ABRXMLSearchSoap {

    @WebResult(name = "SearchByABNv201205Response", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/", partName = "parameters")
    @WebMethod(operationName = "SearchByABNv201205", action = "http://abr.business.gov.au/ABRXMLSearch/SearchByABNv201205")
    public SearchByABNv201205Response searchByABNv201205(
        @WebParam(partName = "parameters", name = "SearchByABNv201205", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        SearchByABNv201205 parameters
    );

    @WebResult(name = "SearchByASICv200506Response", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/", partName = "parameters")
    @WebMethod(operationName = "SearchByASICv200506", action = "http://abr.business.gov.au/ABRXMLSearch/SearchByASICv200506")
    public SearchByASICv200506Response searchByASICv200506(
        @WebParam(partName = "parameters", name = "SearchByASICv200506", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        SearchByASICv200506 parameters
    );

    @WebResult(name = "SearchByCharityResponse", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/", partName = "parameters")
    @WebMethod(operationName = "SearchByCharity", action = "http://abr.business.gov.au/ABRXMLSearch/SearchByCharity")
    public SearchByCharityResponse searchByCharity(
        @WebParam(partName = "parameters", name = "SearchByCharity", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        SearchByCharity parameters
    );

    @WebResult(name = "ABRSearchByNameResponse", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/", partName = "parameters")
    @WebMethod(operationName = "ABRSearchByName", action = "http://abr.business.gov.au/ABRXMLSearch/ABRSearchByName")
    public ABRSearchByNameResponse abrSearchByName(
        @WebParam(partName = "parameters", name = "ABRSearchByName", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        ABRSearchByName parameters
    );

    @WebResult(name = "ABRSearchByNameAdvanced2006Response", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/", partName = "parameters")
    @WebMethod(operationName = "ABRSearchByNameAdvanced2006", action = "http://abr.business.gov.au/ABRXMLSearch/ABRSearchByNameAdvanced2006")
    public ABRSearchByNameAdvanced2006Response abrSearchByNameAdvanced2006(
        @WebParam(partName = "parameters", name = "ABRSearchByNameAdvanced2006", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        ABRSearchByNameAdvanced2006 parameters
    );

    @WebResult(name = "ABRSearchByNameAdvancedSimpleProtocol2012Response", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/", partName = "parameters")
    @WebMethod(operationName = "ABRSearchByNameAdvancedSimpleProtocol2012", action = "http://abr.business.gov.au/ABRXMLSearch/ABRSearchByNameAdvancedSimpleProtocol2012")
    public ABRSearchByNameAdvancedSimpleProtocol2012Response abrSearchByNameAdvancedSimpleProtocol2012(
        @WebParam(partName = "parameters", name = "ABRSearchByNameAdvancedSimpleProtocol2012", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        ABRSearchByNameAdvancedSimpleProtocol2012 parameters
    );

    @WebResult(name = "ABRSearchByASICResponse", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/", partName = "parameters")
    @WebMethod(operationName = "ABRSearchByASIC", action = "http://abr.business.gov.au/ABRXMLSearch/ABRSearchByASIC")
    public ABRSearchByASICResponse abrSearchByASIC(
        @WebParam(partName = "parameters", name = "ABRSearchByASIC", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        ABRSearchByASIC parameters
    );

    @WebResult(name = "SearchByABNv200709Response", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/", partName = "parameters")
    @WebMethod(operationName = "SearchByABNv200709", action = "http://abr.business.gov.au/ABRXMLSearch/SearchByABNv200709")
    public SearchByABNv200709Response searchByABNv200709(
        @WebParam(partName = "parameters", name = "SearchByABNv200709", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        SearchByABNv200709 parameters
    );

    @WebResult(name = "ABRSearchByNameAdvancedResponse", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/", partName = "parameters")
    @WebMethod(operationName = "ABRSearchByNameAdvanced", action = "http://abr.business.gov.au/ABRXMLSearch/ABRSearchByNameAdvanced")
    public ABRSearchByNameAdvancedResponse abrSearchByNameAdvanced(
        @WebParam(partName = "parameters", name = "ABRSearchByNameAdvanced", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        ABRSearchByNameAdvanced parameters
    );

    @WebResult(name = "SearchByABNv200506Response", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/", partName = "parameters")
    @WebMethod(operationName = "SearchByABNv200506", action = "http://abr.business.gov.au/ABRXMLSearch/SearchByABNv200506")
    public SearchByABNv200506Response searchByABNv200506(
        @WebParam(partName = "parameters", name = "SearchByABNv200506", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        SearchByABNv200506 parameters
    );

    @WebResult(name = "SearchByASICv201205Response", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/", partName = "parameters")
    @WebMethod(operationName = "SearchByASICv201205", action = "http://abr.business.gov.au/ABRXMLSearch/SearchByASICv201205")
    public SearchByASICv201205Response searchByASICv201205(
        @WebParam(partName = "parameters", name = "SearchByASICv201205", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        SearchByASICv201205 parameters
    );

    @WebResult(name = "SearchByABNStatusResponse", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/", partName = "parameters")
    @WebMethod(operationName = "SearchByABNStatus", action = "http://abr.business.gov.au/ABRXMLSearch/SearchByABNStatus")
    public SearchByABNStatusResponse searchByABNStatus(
        @WebParam(partName = "parameters", name = "SearchByABNStatus", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        SearchByABNStatus parameters
    );

    @WebResult(name = "ABRSearchByNameAdvancedSimpleProtocol2006Response", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/", partName = "parameters")
    @WebMethod(operationName = "ABRSearchByNameAdvancedSimpleProtocol2006", action = "http://abr.business.gov.au/ABRXMLSearch/ABRSearchByNameAdvancedSimpleProtocol2006")
    public ABRSearchByNameAdvancedSimpleProtocol2006Response abrSearchByNameAdvancedSimpleProtocol2006(
        @WebParam(partName = "parameters", name = "ABRSearchByNameAdvancedSimpleProtocol2006", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        ABRSearchByNameAdvancedSimpleProtocol2006 parameters
    );

    @WebResult(name = "ABRSearchByABNResponse", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/", partName = "parameters")
    @WebMethod(operationName = "ABRSearchByABN", action = "http://abr.business.gov.au/ABRXMLSearch/ABRSearchByABN")
    public ABRSearchByABNResponse abrSearchByABN(
        @WebParam(partName = "parameters", name = "ABRSearchByABN", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        ABRSearchByABN parameters
    );

    @WebResult(name = "ABRSearchByNameSimpleProtocolResponse", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/", partName = "parameters")
    @WebMethod(operationName = "ABRSearchByNameSimpleProtocol", action = "http://abr.business.gov.au/ABRXMLSearch/ABRSearchByNameSimpleProtocol")
    public ABRSearchByNameSimpleProtocolResponse abrSearchByNameSimpleProtocol(
        @WebParam(partName = "parameters", name = "ABRSearchByNameSimpleProtocol", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        ABRSearchByNameSimpleProtocol parameters
    );

    @WebResult(name = "SearchByRegistrationEventResponse", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/", partName = "parameters")
    @WebMethod(operationName = "SearchByRegistrationEvent", action = "http://abr.business.gov.au/ABRXMLSearch/SearchByRegistrationEvent")
    public SearchByRegistrationEventResponse searchByRegistrationEvent(
        @WebParam(partName = "parameters", name = "SearchByRegistrationEvent", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        SearchByRegistrationEvent parameters
    );

    @WebResult(name = "SearchByPostcodeResponse", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/", partName = "parameters")
    @WebMethod(operationName = "SearchByPostcode", action = "http://abr.business.gov.au/ABRXMLSearch/SearchByPostcode")
    public SearchByPostcodeResponse searchByPostcode(
        @WebParam(partName = "parameters", name = "SearchByPostcode", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        SearchByPostcode parameters
    );

    @WebResult(name = "ABRSearchByNameAdvancedSimpleProtocolResponse", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/", partName = "parameters")
    @WebMethod(operationName = "ABRSearchByNameAdvancedSimpleProtocol", action = "http://abr.business.gov.au/ABRXMLSearch/ABRSearchByNameAdvancedSimpleProtocol")
    public ABRSearchByNameAdvancedSimpleProtocolResponse abrSearchByNameAdvancedSimpleProtocol(
        @WebParam(partName = "parameters", name = "ABRSearchByNameAdvancedSimpleProtocol", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        ABRSearchByNameAdvancedSimpleProtocol parameters
    );

    @WebResult(name = "ABRSearchByNameAdvanced2012Response", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/", partName = "parameters")
    @WebMethod(operationName = "ABRSearchByNameAdvanced2012", action = "http://abr.business.gov.au/ABRXMLSearch/ABRSearchByNameAdvanced2012")
    public ABRSearchByNameAdvanced2012Response abrSearchByNameAdvanced2012(
        @WebParam(partName = "parameters", name = "ABRSearchByNameAdvanced2012", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        ABRSearchByNameAdvanced2012 parameters
    );

    @WebResult(name = "SearchByUpdateEventResponse", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/", partName = "parameters")
    @WebMethod(operationName = "SearchByUpdateEvent", action = "http://abr.business.gov.au/ABRXMLSearch/SearchByUpdateEvent")
    public SearchByUpdateEventResponse searchByUpdateEvent(
        @WebParam(partName = "parameters", name = "SearchByUpdateEvent", targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/")
        SearchByUpdateEvent parameters
    );
}
