
/*
 * 
 */

package au.net.transtech.tuan.pojo.abn;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.3
 * Fri Sep 05 00:13:56 EST 2014
 * Generated source version: 2.2.3
 * 
 */


@WebServiceClient(name = "ABRXMLSearch", 
                  wsdlLocation = "file:/home/tuan/workspace/simple-pojo/src/main/resources/abn/abn.wsdl",
                  targetNamespace = "http://abr.business.gov.au/ABRXMLSearch/") 
public class ABRXMLSearch extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://abr.business.gov.au/ABRXMLSearch/", "ABRXMLSearch");
    public final static QName ABRXMLSearchSoap = new QName("http://abr.business.gov.au/ABRXMLSearch/", "ABRXMLSearchSoap");
    public final static QName ABRXMLSearchSoap12 = new QName("http://abr.business.gov.au/ABRXMLSearch/", "ABRXMLSearchSoap12");
    public final static QName ABRXMLSearchHttpGet = new QName("http://abr.business.gov.au/ABRXMLSearch/", "ABRXMLSearchHttpGet");
    public final static QName ABRXMLSearchHttpPost = new QName("http://abr.business.gov.au/ABRXMLSearch/", "ABRXMLSearchHttpPost");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/tuan/workspace/simple-pojo/src/main/resources/abn/abn.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:/home/tuan/workspace/simple-pojo/src/main/resources/abn/abn.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public ABRXMLSearch(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ABRXMLSearch(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ABRXMLSearch() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns ABRXMLSearchSoap
     */
    @WebEndpoint(name = "ABRXMLSearchSoap")
    public ABRXMLSearchSoap getABRXMLSearchSoap() {
        return super.getPort(ABRXMLSearchSoap, ABRXMLSearchSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ABRXMLSearchSoap
     */
    @WebEndpoint(name = "ABRXMLSearchSoap")
    public ABRXMLSearchSoap getABRXMLSearchSoap(WebServiceFeature... features) {
        return super.getPort(ABRXMLSearchSoap, ABRXMLSearchSoap.class, features);
    }
    /**
     * 
     * @return
     *     returns ABRXMLSearchSoap
     */
    @WebEndpoint(name = "ABRXMLSearchSoap12")
    public ABRXMLSearchSoap getABRXMLSearchSoap12() {
        return super.getPort(ABRXMLSearchSoap12, ABRXMLSearchSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ABRXMLSearchSoap
     */
    @WebEndpoint(name = "ABRXMLSearchSoap12")
    public ABRXMLSearchSoap getABRXMLSearchSoap12(WebServiceFeature... features) {
        return super.getPort(ABRXMLSearchSoap12, ABRXMLSearchSoap.class, features);
    }
    /**
     * 
     * @return
     *     returns ABRXMLSearchHttpGet
     */
    @WebEndpoint(name = "ABRXMLSearchHttpGet")
    public ABRXMLSearchHttpGet getABRXMLSearchHttpGet() {
        return super.getPort(ABRXMLSearchHttpGet, ABRXMLSearchHttpGet.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ABRXMLSearchHttpGet
     */
    @WebEndpoint(name = "ABRXMLSearchHttpGet")
    public ABRXMLSearchHttpGet getABRXMLSearchHttpGet(WebServiceFeature... features) {
        return super.getPort(ABRXMLSearchHttpGet, ABRXMLSearchHttpGet.class, features);
    }
    /**
     * 
     * @return
     *     returns ABRXMLSearchHttpPost
     */
    @WebEndpoint(name = "ABRXMLSearchHttpPost")
    public ABRXMLSearchHttpPost getABRXMLSearchHttpPost() {
        return super.getPort(ABRXMLSearchHttpPost, ABRXMLSearchHttpPost.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ABRXMLSearchHttpPost
     */
    @WebEndpoint(name = "ABRXMLSearchHttpPost")
    public ABRXMLSearchHttpPost getABRXMLSearchHttpPost(WebServiceFeature... features) {
        return super.getPort(ABRXMLSearchHttpPost, ABRXMLSearchHttpPost.class, features);
    }

}
